// generated by Fast Light User Interface Designer (fluid) version 1.0405

#ifndef gui_generated_h
#define gui_generated_h
#include <FL/Fl.H>
#include "resizable_image.h"
#include "gui_callback.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
extern Fl_Group *Sidebar;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *MonitorCutoffCheckbox;
#include <FL/Fl_Box.H>
extern Fl_Box *ResolutionDisplay;
extern Fl_Box *SkinFrameCountDisplay;
extern Fl_Check_Button *ScanlineCheckbox;
extern Fl_Check_Button *ScrollingCheckbox;
extern Fl_Check_Button *HorizontalScrollingCheckbox;
extern Fl_Check_Button *AnimatedCheckbox;
#include <FL/Fl_Spinner.H>
extern Fl_Spinner *FPSInput;
extern Fl_Spinner *ScrollRateInput;
extern Fl_Box *SkinCountDisplay;
extern Fl_Box *TotalFrameCountDisplay;
#include <FL/Fl_Input.H>
extern Fl_Input *ModelNameTextInput;
#include <FL/Fl_Choice.H>
extern Fl_Choice *PoseSelector;
#include <FL/Fl_Button.H>
extern Fl_Button *ExportButton;
extern MonitorAspectOutlineImage *PreviewImage;
extern Fl_Button *LoadImageButton;
extern Fl_Button *PlayAnimation;
extern Fl_Spinner *PreviewSkinSelector;
extern Fl_Button *AddSkinButton;
extern Fl_Button *RemoveSkinButton;
extern Fl_Spinner *PreviewFrameSelector;
extern Fl_Button *AddFrameButton;
extern Fl_Button *RemoveFrameButton;
extern "C" { Fl_Double_Window* init(); }
extern Fl_Menu_Item menu_PoseSelector[];
#endif
