// generated by Fast Light User Interface Designer (fluid) version 1.0405

#include "gui_generated.h"
#include <FL/Fl_PNG_Image.H>

unsigned char appIcon[1565] = /* data inlined from ../../assets/MonMakeLogo_32.png */
{137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,32,0,0,0,32,8,3,0,0,0,
68,164,138,198,0,0,0,1,115,82,71,66,1,217,201,44,127,0,0,0,9,112,72,89,115,0,0,
11,19,0,0,11,19,1,0,154,156,24,0,0,2,166,80,76,84,69,0,0,0,19,8,1,22,10,1,25,
12,2,23,11,2,24,11,2,26,12,2,16,7,1,20,9,1,27,13,2,21,10,1,17,7,1,34,18,2,14,6,
1,32,17,2,13,5,1,30,16,2,172,132,0,29,14,2,25,11,2,11,5,1,10,4,1,52,34,1,61,
41,1,8,3,0,59,39,1,103,75,0,186,143,0,76,53,1,41,23,2,66,45,1,45,29,1,146,111,
0,56,37,1,36,19,2,151,147,144,29,29,29,168,129,0,34,35,35,182,176,172,32,33,
34,38,28,20,56,45,37,176,170,168,140,106,0,185,180,176,205,158,0,157,150,143,
152,116,0,194,188,183,175,135,0,32,31,32,147,139,133,26,14,5,96,70,1,163,157,
151,180,173,169,70,49,1,191,188,182,60,50,42,211,164,0,120,89,1,135,101,0,29,17,
8,62,57,53,50,32,1,106,79,1,87,62,0,74,52,1,13,7,4,92,66,1,99,73,1,39,39,39,
37,22,1,170,131,0,30,32,32,104,99,97,28,26,28,143,140,133,112,83,1,104,97,90,
196,192,187,177,173,168,57,60,60,136,135,134,170,164,162,163,159,152,58,60,61,
145,141,136,178,173,169,92,92,91,58,57,57,49,52,54,193,188,184,127,122,117,92,
88,85,185,179,175,46,46,45,30,29,30,192,184,183,197,192,188,80,73,68,97,93,89,
115,107,100,161,156,154,46,48,49,88,62,1,44,37,32,90,83,77,145,139,137,183,184,
175,121,116,113,191,188,182,79,75,72,170,167,162,57,58,58,32,32,33,155,152,146,
192,188,184,127,95,0,150,146,143,91,85,82,105,100,97,57,53,50,195,190,186,181,
176,172,185,178,173,132,128,125,113,109,106,86,82,79,218,169,0,46,40,38,26,27,
26,198,193,189,181,175,171,70,65,61,200,196,190,161,154,151,105,96,89,202,156,
0,33,28,25,71,71,72,110,103,96,196,190,187,75,70,66,81,58,0,151,145,143,192,
184,182,58,59,59,170,164,162,31,31,31,152,146,144,32,22,15,172,165,158,54,49,46,
53,55,57,173,166,160,190,183,181,135,131,125,122,114,106,163,124,0,189,184,180,
100,91,84,179,174,171,202,199,193,189,185,181,69,61,53,18,13,10,180,138,0,38,31,
26,168,164,158,31,32,33,139,135,132,152,145,139,74,64,57,24,17,14,28,27,28,189,
185,181,193,189,185,157,151,149,36,36,36,188,182,178,182,179,173,88,80,73,187,
181,178,192,188,183,195,190,186,196,191,187,61,64,66,111,102,94,114,107,101,52,
40,31,182,179,174,62,62,63,197,193,188,191,188,182,186,178,172,179,176,171,143,
137,132,67,63,60,183,178,173,202,194,189,76,66,59,43,31,22,43,28,1,70,66,63,156,
151,147,154,150,147,65,55,48,38,32,28,91,82,75,45,35,26,93,85,78,192,187,183,
184,142,0,54,58,59,122,116,111,61,51,45,188,184,179,221,172,0,186,181,175,79,55,
1,34,34,35,60,55,52,193,188,182,181,174,172,45,85,5,211,0,0,0,226,116,82,78,
83,0,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,2,168,255,234,
51,72,255,255,3,255,80,255,255,255,96,255,3,255,255,255,255,255,255,2,255,255,
255,255,255,255,255,255,255,255,255,255,255,255,255,255,121,121,25,154,255,203,
183,18,253,244,69,137,217,65,242,244,176,43,143,177,174,90,198,40,12,217,234,
147,255,117,255,255,255,216,87,8,211,41,227,3,68,106,146,112,255,25,251,232,255,
164,38,253,192,97,201,255,255,67,235,65,239,2,170,255,255,255,62,196,195,255,
255,56,31,59,147,151,86,255,87,255,251,120,60,169,255,255,103,255,7,16,247,251,
255,255,255,128,255,190,255,248,255,161,122,154,59,255,70,100,229,88,173,205,34,
224,255,190,255,58,64,226,50,45,12,162,255,255,242,244,255,255,250,89,28,255,
255,222,255,255,17,255,255,255,255,251,255,255,255,255,255,4,4,76,230,85,105,0,
0,2,34,73,68,65,84,120,156,99,96,24,18,64,185,190,116,174,21,62,5,21,199,93,
179,83,227,182,93,197,169,96,82,181,8,47,59,227,140,101,1,97,135,177,27,52,189,
153,159,151,155,81,158,137,203,84,107,251,188,132,100,76,5,25,61,32,5,206,82,46,
98,158,172,44,154,235,250,86,21,160,41,152,186,156,159,157,145,145,209,83,81,
206,9,168,136,143,197,222,250,210,49,221,60,36,5,157,162,64,39,112,112,49,49,
177,8,136,73,202,185,153,41,10,49,179,158,62,181,111,206,100,152,130,53,80,5,44,
194,204,204,172,172,142,226,226,150,82,226,142,2,44,246,55,115,252,182,62,0,41,
200,135,41,96,101,102,150,103,115,44,151,17,224,145,113,182,157,168,120,134,145,
123,101,123,4,80,65,21,200,141,16,5,146,170,10,6,130,94,158,64,147,120,196,229,
204,24,217,249,37,26,128,1,89,201,205,8,116,0,208,9,172,194,60,10,130,130,170,
130,10,254,242,108,204,194,44,204,28,64,5,62,12,12,231,39,112,51,49,115,130,0,
27,27,155,173,160,19,167,165,151,160,14,27,27,51,43,19,7,55,191,68,26,3,195,
102,7,17,118,14,102,33,1,62,32,200,146,94,97,199,201,172,35,232,206,9,86,192,
200,43,26,207,192,112,238,62,40,164,25,153,216,4,120,148,100,165,109,244,22,216,
25,25,201,128,77,224,2,42,104,100,96,152,121,210,194,228,138,38,208,149,92,44,
108,66,60,178,6,183,155,108,186,165,121,56,217,32,10,10,129,190,120,120,196,176,
166,213,194,100,209,101,38,22,32,80,188,166,119,215,205,140,135,71,64,136,153,
139,145,93,228,108,7,36,176,180,107,119,108,58,116,98,109,215,126,86,22,62,49,
97,54,33,62,37,37,30,62,33,86,70,254,89,75,16,65,94,18,173,27,155,114,71,127,
175,22,48,60,89,88,217,132,4,4,56,89,184,47,238,134,203,183,204,14,222,160,162,
146,24,21,178,171,78,63,221,218,20,232,4,14,14,14,238,245,234,112,5,49,225,215,
239,109,241,240,200,220,195,16,212,182,177,255,150,249,252,11,44,220,188,34,34,
161,112,5,190,106,106,197,7,123,167,104,104,128,121,71,15,148,5,46,53,191,225,
224,154,11,87,48,109,181,55,90,66,89,172,190,112,103,164,33,156,107,156,100,140,
153,218,24,138,180,177,8,210,29,0,0,22,99,118,80,59,35,98,27,0,0,0,0,73,69,78,
68,174,66,96,130};

Fl_Group *Sidebar=(Fl_Group *)0;

Fl_Check_Button *MonitorCutoffCheckbox=(Fl_Check_Button *)0;

static void cb_MonitorCutoffCheckbox(Fl_Check_Button* o, void*) {
  PreviewImage->TogglePreviewFromCheckbox(o);
}

Fl_Box *ResolutionDisplay=(Fl_Box *)0;

Fl_Box *SkinFrameCountDisplay=(Fl_Box *)0;

Fl_Check_Button *ScanlineCheckbox=(Fl_Check_Button *)0;

static void cb_ScanlineCheckbox(Fl_Check_Button* o, void*) {
  ScanlineCheckboxCallback(o);
}

Fl_Check_Button *ScrollingCheckbox=(Fl_Check_Button *)0;

static void cb_ScrollingCheckbox(Fl_Check_Button* o, void*) {
  ScrollingCheckboxCallback(o);
}

Fl_Check_Button *HorizontalScrollingCheckbox=(Fl_Check_Button *)0;

static void cb_HorizontalScrollingCheckbox(Fl_Check_Button* o, void*) {
  HorizontalScrollingCheckboxCallback(o);
}

Fl_Check_Button *AnimatedCheckbox=(Fl_Check_Button *)0;

static void cb_AnimatedCheckbox(Fl_Check_Button* o, void*) {
  AnimatedCheckboxCallback(o);
}

Fl_Spinner *FPSInput=(Fl_Spinner *)0;

static void cb_FPSInput(Fl_Spinner* o, void*) {
  FPSInputCallback(o);
}

Fl_Spinner *ScrollRateInput=(Fl_Spinner *)0;

static void cb_ScrollRateInput(Fl_Spinner* o, void*) {
  ScrollRateInputCallback(o);
}

Fl_Box *SkinCountDisplay=(Fl_Box *)0;

Fl_Box *TotalFrameCountDisplay=(Fl_Box *)0;

Fl_Input *ModelNameTextInput=(Fl_Input *)0;

static void cb_ModelNameTextInput(Fl_Input* o, void*) {
  ModelNameTextInputCallback(o);
}

Fl_Choice *PoseSelector=(Fl_Choice *)0;

static void cb_PoseSelector(Fl_Choice* o, void*) {
  PoseSelectorCallback(o);
}

Fl_Menu_Item menu_PoseSelector[] = {
 {"Angled", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Straight", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Button *ExportButton=(Fl_Button *)0;

static void cb_ExportButton(Fl_Button* o, void*) {
  ExportCallback(o);
}

MonitorAspectOutlineImage *PreviewImage=(MonitorAspectOutlineImage *)0;

Fl_Button *LoadImageButton=(Fl_Button *)0;

static void cb_LoadImageButton(Fl_Button* o, void*) {
  LoadImageCallback(o);
}

Fl_Button *PlayAnimation=(Fl_Button *)0;

static void cb_PlayAnimation(Fl_Button* o, void*) {
  PlayAnimationCallback(o);
}

Fl_Spinner *PreviewSkinSelector=(Fl_Spinner *)0;

static void cb_PreviewSkinSelector(Fl_Spinner* o, void*) {
  SkinSelectorCallback(o);
}

Fl_Button *AddSkinButton=(Fl_Button *)0;

static void cb_AddSkinButton(Fl_Button* o, void*) {
  AddSkinCallback(o);
}

Fl_Button *RemoveSkinButton=(Fl_Button *)0;

static void cb_RemoveSkinButton(Fl_Button* o, void*) {
  RemoveCurrentSkinCallback(o);
}

Fl_Spinner *PreviewFrameSelector=(Fl_Spinner *)0;

static void cb_PreviewFrameSelector(Fl_Spinner* o, void*) {
  FrameSelectorCallback(o);
}

Fl_Button *AddFrameButton=(Fl_Button *)0;

static void cb_AddFrameButton(Fl_Button* o, void*) {
  AddFrameCallback(o);
}

Fl_Button *RemoveFrameButton=(Fl_Button *)0;

static void cb_RemoveFrameButton(Fl_Button* o, void*) {
  RemoveCurrentFrameCallback(o);
}

Fl_Double_Window* init() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(1270, 910, "Portal 2 Monitor Maker");
    w = o; (void)w;
    o->color((Fl_Color)55);
    o->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Sidebar = new Fl_Group(0, 0, 399, 910);
      Sidebar->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      { MonitorCutoffCheckbox = new Fl_Check_Button(15, 22, 20, 25, "Preview monitor cutoff");
        MonitorCutoffCheckbox->down_box(FL_DOWN_BOX);
        MonitorCutoffCheckbox->callback((Fl_Callback*)cb_MonitorCutoffCheckbox);
        MonitorCutoffCheckbox->align(Fl_Align(FL_ALIGN_RIGHT));
      } // Fl_Check_Button* MonitorCutoffCheckbox
      { Fl_Box* o = new Fl_Box(15, 272, 140, 25, "Selected skin");
        o->labelfont(1);
        o->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
      } // Fl_Box* o
      { ResolutionDisplay = new Fl_Box(15, 302, 205, 25, "Resolution: 512x512");
        ResolutionDisplay->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
      } // Fl_Box* ResolutionDisplay
      { SkinFrameCountDisplay = new Fl_Box(15, 332, 205, 25, "Frames in selected skin: 1");
        SkinFrameCountDisplay->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
      } // Fl_Box* SkinFrameCountDisplay
      { ScanlineCheckbox = new Fl_Check_Button(15, 362, 20, 25, "Add scanline effect? ");
        ScanlineCheckbox->down_box(FL_DOWN_BOX);
        ScanlineCheckbox->callback((Fl_Callback*)cb_ScanlineCheckbox);
        ScanlineCheckbox->align(Fl_Align(FL_ALIGN_RIGHT));
      } // Fl_Check_Button* ScanlineCheckbox
      { ScrollingCheckbox = new Fl_Check_Button(15, 387, 20, 25, "Make image scroll?");
        ScrollingCheckbox->down_box(FL_DOWN_BOX);
        ScrollingCheckbox->callback((Fl_Callback*)cb_ScrollingCheckbox);
        ScrollingCheckbox->align(Fl_Align(FL_ALIGN_RIGHT));
      } // Fl_Check_Button* ScrollingCheckbox
      { HorizontalScrollingCheckbox = new Fl_Check_Button(180, 387, 20, 25, "Horizontal?");
        HorizontalScrollingCheckbox->down_box(FL_DOWN_BOX);
        HorizontalScrollingCheckbox->callback((Fl_Callback*)cb_HorizontalScrollingCheckbox);
        HorizontalScrollingCheckbox->align(Fl_Align(FL_ALIGN_RIGHT));
      } // Fl_Check_Button* HorizontalScrollingCheckbox
      { AnimatedCheckbox = new Fl_Check_Button(15, 412, 20, 25, "Make animated? ");
        AnimatedCheckbox->down_box(FL_DOWN_BOX);
        AnimatedCheckbox->callback((Fl_Callback*)cb_AnimatedCheckbox);
        AnimatedCheckbox->align(Fl_Align(FL_ALIGN_RIGHT));
      } // Fl_Check_Button* AnimatedCheckbox
      { FPSInput = new Fl_Spinner(15, 442, 40, 25, " FPS");
        FPSInput->maximum(60);
        FPSInput->value(24);
        FPSInput->callback((Fl_Callback*)cb_FPSInput);
        FPSInput->align(Fl_Align(FL_ALIGN_RIGHT));
      } // Fl_Spinner* FPSInput
      { ScrollRateInput = new Fl_Spinner(15, 472, 55, 25, " Scroll Speed");
        ScrollRateInput->type(1);
        ScrollRateInput->minimum(0.05);
        ScrollRateInput->maximum(1);
        ScrollRateInput->step(0.05);
        ScrollRateInput->value(0.2);
        ScrollRateInput->callback((Fl_Callback*)cb_ScrollRateInput);
        ScrollRateInput->align(Fl_Align(FL_ALIGN_RIGHT));
      } // Fl_Spinner* ScrollRateInput
      { SkinCountDisplay = new Fl_Box(15, 697, 205, 25, "Skins: 1");
        SkinCountDisplay->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
      } // Fl_Box* SkinCountDisplay
      { TotalFrameCountDisplay = new Fl_Box(15, 722, 205, 25, "Total frames: 1");
        TotalFrameCountDisplay->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
      } // Fl_Box* TotalFrameCountDisplay
      { Fl_Box* o = new Fl_Box(15, 747, 205, 25, "Model name:");
        o->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
      } // Fl_Box* o
      { ModelNameTextInput = new Fl_Input(15, 772, 380, 25);
        ModelNameTextInput->callback((Fl_Callback*)cb_ModelNameTextInput);
        ModelNameTextInput->align(Fl_Align(FL_ALIGN_RIGHT));
      } // Fl_Input* ModelNameTextInput
      { Fl_Box* o = new Fl_Box(15, 801, 205, 25, "Monitor Shape:");
        o->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
      } // Fl_Box* o
      { PoseSelector = new Fl_Choice(15, 827, 92, 22);
        PoseSelector->down_box(FL_BORDER_BOX);
        PoseSelector->callback((Fl_Callback*)cb_PoseSelector);
        PoseSelector->align(Fl_Align(FL_ALIGN_RIGHT));
        PoseSelector->menu(menu_PoseSelector);
      } // Fl_Choice* PoseSelector
      { ExportButton = new Fl_Button(15, 870, 85, 25, "Export");
        ExportButton->box(FL_GLEAM_THIN_UP_BOX);
        ExportButton->color((Fl_Color)55);
        ExportButton->selection_color(FL_INACTIVE_COLOR);
        ExportButton->callback((Fl_Callback*)cb_ExportButton);
      } // Fl_Button* ExportButton
      Sidebar->end();
    } // Fl_Group* Sidebar
    { Fl_Group* o = new Fl_Group(399, 5, 866, 900);
      o->align(Fl_Align(FL_ALIGN_TOP_RIGHT));
      { PreviewImage = new MonitorAspectOutlineImage(405, 45, 850, 850, "No Image Loaded");
        PreviewImage->box(FL_FLAT_BOX);
        PreviewImage->color(FL_LIGHT3);
        PreviewImage->selection_color(FL_BACKGROUND_COLOR);
        PreviewImage->labeltype(FL_NORMAL_LABEL);
        PreviewImage->labelfont(0);
        PreviewImage->labelsize(14);
        PreviewImage->labelcolor(FL_FOREGROUND_COLOR);
        PreviewImage->align(Fl_Align(512));
        PreviewImage->when(FL_WHEN_RELEASE);
      } // MonitorAspectOutlineImage* PreviewImage
      { LoadImageButton = new Fl_Button(730, 15, 200, 25, "Load image for frame");
        LoadImageButton->color((Fl_Color)55);
        LoadImageButton->callback((Fl_Callback*)cb_LoadImageButton);
      } // Fl_Button* LoadImageButton
      { PlayAnimation = new Fl_Button(1065, 15, 25, 25, "\342\226\272");
        PlayAnimation->callback((Fl_Callback*)cb_PlayAnimation);
      } // Fl_Button* PlayAnimation
      { PreviewSkinSelector = new Fl_Spinner(445, 15, 40, 25, "Skin:");
        PreviewSkinSelector->minimum(0);
        PreviewSkinSelector->maximum(30);
        PreviewSkinSelector->value(0);
        PreviewSkinSelector->callback((Fl_Callback*)cb_PreviewSkinSelector);
      } // Fl_Spinner* PreviewSkinSelector
      { AddSkinButton = new Fl_Button(490, 15, 25, 25, "+");
        AddSkinButton->callback((Fl_Callback*)cb_AddSkinButton);
      } // Fl_Button* AddSkinButton
      { RemoveSkinButton = new Fl_Button(520, 15, 25, 25, "-");
        RemoveSkinButton->callback((Fl_Callback*)cb_RemoveSkinButton);
      } // Fl_Button* RemoveSkinButton
      { PreviewFrameSelector = new Fl_Spinner(1150, 15, 40, 25, "Frame:");
        PreviewFrameSelector->callback((Fl_Callback*)cb_PreviewFrameSelector);
      } // Fl_Spinner* PreviewFrameSelector
      { AddFrameButton = new Fl_Button(1195, 15, 25, 25, "+");
        AddFrameButton->callback((Fl_Callback*)cb_AddFrameButton);
      } // Fl_Button* AddFrameButton
      { RemoveFrameButton = new Fl_Button(1225, 15, 25, 25, "-");
        RemoveFrameButton->callback((Fl_Callback*)cb_RemoveFrameButton);
      } // Fl_Button* RemoveFrameButton
      o->end();
    } // Fl_Group* o
    o->resizable(o);
    o->icon(new Fl_PNG_Image("MonMakeIcon.png", appIcon, sizeof(appIcon)));
    o->end();
  } // Fl_Double_Window* o
  return w;
}
